services:
  # mysql:
  #   image: 'mysql:latest'
  #   environment:
  #     - 'MYSQL_DATABASE=mydatabase'
  #     - 'MYSQL_PASSWORD=secret'
  #     - 'MYSQL_ROOT_PASSWORD=verysecret'
  #     - 'MYSQL_USER=myuser'
  #   ports:
  #     - '3306'
  # postgres:
  #   image: 'postgres:latest'
  #   environment:
  #     - 'POSTGRES_DB=mydatabase'
  #     - 'POSTGRES_PASSWORD=secret'
  #     - 'POSTGRES_USER=myuser'
  #   ports:
  #     - '5432'
  # rabbitmq:
  #   image: 'rabbitmq:latest'
  #   environment:
  #     - 'RABBITMQ_DEFAULT_PASS=secret'
  #     - 'RABBITMQ_DEFAULT_USER=myuser'
  #   ports:
  #     - '5672'
  redis:
    image: 'redis:latest'
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /configs/redis:/var/lib/redis
      - /configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
  # sqlserver:
  #   image: 'mcr.microsoft.com/mssql/server:latest'
  #   environment:
  #     - 'ACCEPT_EULA=yes'
  #     - 'MSSQL_PID=express'
  #     - 'MSSQL_SA_PASSWORD=verYs3cret'
  #   ports:
  #     - '1433'

  app:
    build:
      context: .
      # dockerfile: Dockerfile
      dockerfile: DockerfileDev # for development only
    container_name: green-saphire
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - ~/.gradle:/home/gradle/.gradle  # Cache Gradle dependencies
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: 'password'
    restart: always
    depends_on:
      - redis
